BASE_IMAGE=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7d7cb4288eae61535e8f6c538793ba2c613f8b37eeceba9726116150452eacaf
D_OS=rhcos4.17
D_ARCH=aarch64
D_CONTAINER_VER=0
D_DOCA_VERSION=2.10.0
D_OFED_VERSION=25.01-0.6.0.0
D_KERNEL_VER=5.14.0-427.50.1.el9_4.aarch64
D_OFED_SRC_DOWNLOAD_PATH=/run/mellanox/src
OFED_SRC_LOCAL_DIR=/run/mellanox/src/MLNX_OFED_SRC-25.01-0.6.0.0
